### ISSUE TITLE
Hide Error Log when there are 0 errors

### ISSUE THREAD

**Issue by Aktimoose** [hiimjustin000/MoreIcons#10]
this button is entirely useless when there are no errors i'd like it eradicated and out of my sight
![image](https://github.com/user-attachments/assets/8807da46-0fa8-4500-a3fe-2844ae8f6e73)

unless i'm misunderstanding what this button does but currently it's a very large empty menu i don't care about
![image](https://github.com/user-attachments/assets/039d68bb-3a34-4b98-8854-fb5a703a7f5b)

**Comment by Aktimoose** [comment]
feels very obtrusive and unnecessary of a button just for those two things when the folder can be accessed otherwise, would be good as an option to hide it conditionally

**Comment by hiimjustin000** [comment]
Well then... If you insist
