### ISSUE TITLE
Texture Pack Support

### ISSUE THREAD

**Issue by CharlGD1** [hiimjustin000/MoreIcons#13]
Is it possible to be able to make adding more icons/trails through texture packs?

**Comment by hiimjustin000** [comment]
It's already in the mod

**Comment by fibberclip** [comment]
> Is it possible to be able to make adding more icons/trails through texture packs?

Read the mod's description ...
![Screenshot_2024-10-20-13-35-45-216_com android chrome-edit](https://github.com/user-attachments/assets/9889a50d-8127-446d-a39c-94235ec988fa)

**Comment by CharlGD1** [comment]
ah my bad i was just forgetting to add the config folder
