### ISSUE TITLE
Pack credits only exist for Cubes

### ISSUE THREAD

**Issue by fibberclip** [hiimjustin000/MoreIcons#14]
The small pack credits that show under the Icon's name only show up for cubes, other vehicles do not seem to have it (These are all icons added in the same pack through texture loader)

![image](https://github.com/user-attachments/assets/cd64c9db-bb29-4f51-90fd-9aaf98458948)
![image](https://github.com/user-attachments/assets/b8f5365c-8eed-41e6-8ec3-e0832c54eda2)

Very minor issue but lol

**Comment by hiimjustin000** [comment]
Fixed in v1.4.0 (d5d4e14)
