### ISSUE TITLE
Question about More Icons API ( ?

### ISSUE THREAD

**Issue by Naxrin** [hiimjustin000/MoreIcons#16]
How to create a **GJItemIcon** object in my own mod and set the icon style to my current selected if I install More Icons?
Thanks/

**Comment by hiimjustin000** [comment]
```cpp
DispatchEvent<SimplePlayer*, std::string, IconType>("hiimjustin000.more_icons/simple-player", itemIcon->m_player, "my-icon", IconType::Whatever).post();
```

**Comment by Naxrin** [comment]
> ```c++
> DispatchEvent<SimplePlayer*, std::string, IconType>("hiimjustin000.more_icons/simple-player", itemIcon->m_player, "my-icon", IconType::Whatever).post();
> ```

Yeah i read this in your ReadMe, but I get no idea where should i place this dispatch line? (noob im)

**Comment by hiimjustin000** [comment]
This is all you have to do to change the state of an icon. Place it where you want to do it.

**Comment by Naxrin** [comment]
> This is all you have to do to change the state of an icon. Place it where you want to do it.

I write this in my code but my icons are still robtop's, not sure what's missing
GJItemAlpha is the class I inherit from GJItemIcon to cascade the sprites' opacity, while that would probably not matter (tried 
 original GJItemIcon object instead, nothing happened)
not so clear about Dispatch thing so, again thanks for your time
```
            auto icon = GJItemIconAlpha::createBrowserItem(UnlockType(1), gm->getPlayerFrame());
            DispatchEvent<SimplePlayer*, std::string, IconType>("hiimjustin000.more_icons/simple-player", icon->m_player, "my-icon", IconType::Cube).post();
```

**Comment by hiimjustin000** [comment]
"my-icon" has to be replaced with an actual icon name.

**Comment by Naxrin** [comment]
> "my-icon" has to be replaced with an actual icon name.
Okay get it!
