### ISSUE TITLE
Using a trail on mac crashes the game

### ISSUE THREAD

**Issue by FijiAura** [hiimjustin000/MoreIcons#18]
using a custom trail on mac crashes the game

**Comment by hiimjustin000** [comment]
Send the crashlog

**Comment by FijiAura** [comment]
Sorry for the wait,

Sorry for the wait,

> 2024-12-15T16:09:58+0800
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v4.1.0
Loader Commit: 695f39f
Bindings Commit: 16df0dd
Installed mods: 35
Outdated mods: 2
Problems: 0

== Exception Information ==
Faulty Lib: /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash
Faulty Mod: <Unknown>
Instruction Address: 0x102a24227
Signal Code: b (SIGSEGV: Segmentation Fault)

== Stack Trace ==
 - /usr/lib/system/libsystem_platform.dylib + 0x337d: _sigtramp (in libsystem_platform.dylib) + 29
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x560227: 0x0000000102a24227 (in Geometry Dash) + 119
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x2619f5: 0x00000001027259f5 (in Geometry Dash) + 181
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x23d872: cocos2d::CCNode::visit() (in eclipse.eclipse-menu.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x2619dc: 0x00000001027259dc (in Geometry Dash) + 156
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x23d872: cocos2d::CCNode::visit() (in eclipse.eclipse-menu.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x261a40: 0x0000000102725a40 (in Geometry Dash) + 256
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x23d872: cocos2d::CCNode::visit() (in eclipse.eclipse-menu.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x2619dc: 0x00000001027259dc (in Geometry Dash) + 156
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x23d872: cocos2d::CCNode::visit() (in eclipse.eclipse-menu.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x153761: 0x0000000102617761 (in Geometry Dash) + 3313
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x261a40: 0x0000000102725a40 (in Geometry Dash) + 256
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x23d872: cocos2d::CCNode::visit() (in eclipse.eclipse-menu.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xab94d0: 0x102f7d4d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x46ff1f: 0x0000000102933f1f (in Geometry Dash) + 143
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xabb0d0: 0x102f7f0d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/geode.devtools/geode.devtools.dylib + 0x16dd92: cocos2d::CCDirector::drawScene() (in geode.devtools.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xabb0d0: 0x102f7f0d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x248642: cocos2d::CCDirector::drawScene() (in eclipse.eclipse-menu.dylib) + 34
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/geode/unzipped/eclipse.eclipse-menu/eclipse.eclipse-menu.dylib + 0x2177fb: geode::modifier::AsStaticFunction_drawScene<hook177<(anonymous namespace)::hook177Parent>, void (hook177<(anonymous namespace)::hook177Parent>::*)()>::Impl<void (hook177<(anonymous namespace)::hook177Parent>::*)()>::function(hook177<(anonymous namespace)::hook177Parent>*) (in eclipse.eclipse-menu.dylib) + 11
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0xabb0d0: 0x102f7f0d0
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x471d5a: 0x0000000102935d5a (in Geometry Dash) + 42
 - /Users/fijiaura/Library/Application Support/Steam/steamapps/common/Geometry Dash/Geometry Dash.app/Contents/MacOS/Geometry Dash + 0x388fd8: 0x000000010284cfd8 (in Geometry Dash) + 152
 - /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo + 0x3331: CVDisplayLink::performIO(CVTimeStamp*) (in CoreVideo) + 299
 - /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo + 0x2189: CVDisplayLink::runIOThread() (in CoreVideo) + 667
 - /usr/lib/system/libsystem_pthread.dylib + 0x6202: _pthread_start (in libsystem_pthread.dylib) + 99
 - /usr/lib/system/libsystem_pthread.dylib + 0x1bab: thread_start (in libsystem_pthread.dylib) + 15

== Register States ==
rax: 0x7fa2d883c440
rbx: 0x7fa268292470
rcx: 0x60
rdx: 0x303030203030302
rdi: 0
rsi: 0
rbp: 0x309c58d40
rsp: 0x309c58d30
r8: 0x1030200010302
r9: 0x7fa2e7375e01
r10: 0x6000014e4940
r11: 0x388
r12: 0x309c596f8
r13: 0x7fa2a0275000
r14: 0x60000123b440
r15: 0x4d
rip: 0x102a24227
rflags: 0x206
cs: 0x2b
fs: 0
gs: 0

== Installed Mods ==
x | [v1.0.8] alphalaneous.editortab_api
  | [v1.0.6] alphalaneous.improved_song_browser
x | [v1.1.4] alphalaneous.object_summary
x | [v1.0.2] alphalaneous.old_color_triggers
x | [v4.3.1] cvolton.betterinfo
x | [v1.1.0] cvolton.level-id-api
x | [v1.3.1] cvolton.misc_bugfixes
x | [v1.7.2] dankmeme.globed2
x | [v1.0.0-beta.4] eclipse.eclipse-menu
x | [v1.1.2] eclipse.ffmpeg-api
x | [v1.4.4] firee.object-workshop
x | [v1.9.5] firee.prism
x | [v3.0.1] fleym.nongd
x | [v1.4.0-beta.5] gdutilsdevs.gdutils
* | [v1.10.0] geode.custom-keybinds
x | [v1.8.0] geode.devtools
x | [v4.1.0] geode.loader
x | [v1.18.0] geode.node-ids
x | [v1.6.7] geode.texture-loader
x | [v1.3.1] grian.art_importer
x | [v1.4.5] hiimjustin000.demons_in_between
  | [v1.1.0] hiimjustin000.manager_viewer
x | [v1.5.2] hiimjustin000.more_icons
x | [v1.4.1] hjfod.gmd-api
x | [v1.2.0] jouca.badgesapi
x | [v0.2.1-alpha] kampwski.level_tags
x | [v1.2.4] km7dev.gdps-switcher
x | [v1.0.4] km7dev.server_api
x | [v1.3.5] legowiifun.unlisted_objects_in_editor
x | [v1.2.0] ninkaz.blending_glow
* | [v1.0.0-beta.1] rainixgd.geome3dash
  | [v1.0.3] raydeeux.gameobjectidstacksize
x | [v1.0.4] razoom.object_groups
  | [v1.7.6] thesillydoggo.qolmod
x | [v1.3.0] zmx.cbf-lite
