### ISSUE TITLE
Robot fire & particles not showing

### ISSUE THREAD

**Issue by fibberclip** [hiimjustin000/MoreIcons#3]
The mod's causing the robot fire and particles that show up when jumping to either be invisible or just not be rendered at all, this happens regardless of if you're using a vanilla or custom robot, and i've also had it happen on a fresh install of the mod, with no new icons added

https://github.com/user-attachments/assets/c2eec7c5-b2bf-4dbf-a06d-a91c11b0a85b

**Comment by hiimjustin000** [comment]
Oh, I encountered this issue as well, I just chalked it up to something else causing it.

**Comment by fibberclip** [comment]
yeah same, i thought it was a texture pack i had on but i tried on various setups, a different device and asked someone else too

**Comment by hiimjustin000** [comment]
Fixed in v1.2.0 (258b47a)
