### ISSUE TITLE
["Bug"/Suggestion?] Custom Trails by default have blending off

### ISSUE THREAD

**Issue by fibberclip** [hiimjustin000/MoreIcons#5]
"Bug": Any custom trail added has blending off globally, regardless of level settings (vanilla trails are unaffected)

![imagetrail](https://github.com/user-attachments/assets/a41fc6be-40cf-4def-86f5-6b934d88ad16)

Suggestion: There could possibly be a way to config every custom trail to edit 2 attributes:
- Allow Tint (if off: trails can't be tinted by player colors, if on: they're tinted by P2 color like most of vanilla trails. off by default)
- Allow Blending (self explanatory, on by default)

Maybe this could be configurable via a .json file or something associated to each trail (created for each trail on load if it doesn't exist), and **_maybe_** add 2 checkboxes to the trail pop-up that allow for easy modification of these 2 attributes in-game. Although in this case these attributes would most likely be only modified by pack makers that surely know how to edit a file (lol)

**Comment by hiimjustin000** [comment]
Added in v1.2.2 (a700919)

**Comment by fibberclip** [comment]
Reloading textures also resets both options

https://github.com/user-attachments/assets/0b0ee459-0eb7-4b31-b756-c48c8349686e

**Comment by hiimjustin000** [comment]
Fixed in v1.2.3 (b02a83f)
