### ISSUE TITLE
Suggestion: Unlock Conditions and Author Redirects

### ISSUE THREAD

**Issue by Aproxia-dev** [hiimjustin000/MoreIcons#8]
i think it would be kinda cool if you could add unlock conditions and author redirects to the icons.

i ported the No Icon Gradients texture pack over to this mod so i can choose whether i believe the icon looks better with or without the gradients, and i think it would be cool if i still had to get the achievement to unlock the icon. i feel like a simple "if this icon is unlocked, this icon is unlocked too" check would be enough, adding a whole system for achievements would be cool but also feels a little over the top. maybe having a separate mod for achievements with integration could work well, but also i don't think that an achievement mod like that would have a lot of use outside of this mod. at least i can't think of anything.

and by author redirects i just mean that you could do what the main game does and have that "By `name`" thing when you look at the details. perhaps something extra that shows which texture pack adds that specific icon could also be nice.

**Comment by hiimjustin000** [comment]
I really don't like the idea of the unlock conditions, however, I did like the idea of showing which texture pack added the icon, so I did that in v1.3.3 (0ed4808).
